# Generated by Django 4.0.1 on 2022-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstBirthday', models.CharField(max_length=64)),
                ('MonthlyBirthday', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyProfile', models.CharField(max_length=64)),
                ('ProductReview', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FilmEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortFilms', models.CharField(max_length=64)),
                ('Documentaries', models.CharField(max_length=64)),
                ('MusicAlbums', models.CharField(max_length=64)),
                ('FeatureFilms', models.CharField(max_length=64)),
                ('AdFilms', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatureFuntions', models.CharField(max_length=64)),
                ('PregnantSpecial', models.CharField(max_length=64)),
                ('Retirement', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreWedding', models.CharField(max_length=64)),
                ('PostWedding', models.CharField(max_length=64)),
                ('Bride_Bridegroom', models.CharField(max_length=64)),
                ('Haldi', models.CharField(max_length=64)),
                ('Mehandi', models.CharField(max_length=64)),
                ('FinalWedding', models.CharField(max_length=64)),
            ],
        ),
    ]
