# Generated by Django 4.0.1 on 2022-01-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
