# Generated by Django 4.0.1 on 2022-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=64)),
                ('Posting_date', models.CharField(max_length=64)),
                ('Location', models.CharField(max_length=64)),
                ('Offered_salary', models.FloatField()),
                ('Qualification', models.CharField(max_length=64)),
            ],
        ),
    ]
